os: linux
dist: jammy
language: node_js
node_js: "20"

jobs:
  include:
    - stage: install-build
      name: Install And Build
      script:
        - npm install -g yarn
        - yarn set version latest
        - yarn install
        - yarn tsc -b

    - stage: deploy
      name: Publish to npmjs.com
      script: skip
      deploy:
        provider: npm
        email: "xxxxx@xxxxx.com"
        api_token: $npmToken
        cleanup: false
        on:
          tags: true
