os: linux
dist: jammy
language: node_js
node_js: "20"

install: skip
script: sleep 1

deploy:
  provider: npm
  email: "xxxxx@xxxxx.com"  # Replace with your npm email
  api_token: $npmToken       # Ensure that $npmToken is set in your Travis CI settings
  skip_cleanup: true
  on:
    tags: true
